
default: &default
  adapter: postgresql
  hostname: localhost
  pool: 65
  timeout: 8000

development:
  <<: *default
  database: db/development.sqlite3
  database: questions
  username: postgres
  password: 
